%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MY DASHBOARD CV Template
%
% Needs package: Deedy Resume
% XeLaTeX and Sweave Template
%
% Author:
% Martina Manfrin (manfrina87@gmail.com)
%
% License:
% CC BY-NC-SA 3.0 (http://creativecommons.org/licenses/by-nc-sa/3.0/)
%
% Important notes:
% R must be installed on your PC
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\documentclass[a4paper,landscape]{deedy-resume} % Use a4paper, landscape 

\begin{document}
\SweaveOpts{concordance=TRUE}
%----------------------------------------------------------------------------------------
%	TITLE SECTION
%----------------------------------------------------------------------------------------

\lastupdated % Print the Last Updated text at the top right

\namesection{Martina}{Manfrin}{ % Your name
\urlstyle{same}\url{linkedin.com/in/martinamanfrin} \\ % Your website, LinkedIn profile or other web address
\href{mailto:martina.manfrin87@gmail.com}{martina.manfrin87@gmail.com} | 340 7884910 % Your contact information
}


\vspace{5mm}


%----------------------------------------------------------------------------------------
%	LEFT COLUMN
%----------------------------------------------------------------------------------------

\begin{minipage}[t]{0.33\textwidth} % The left column takes up 33% of the text width of the page

%------------------------------------------------
% THAT'S ME!
%------------------------------------------------

\section{That's Me!} 

\fbox{\includegraphics[page=3, scale=0.5, clip, trim=25mm 25mm 0mm 30mm]{Rplots.pdf}}

\sectionspace % Some whitespace after the section

%------------------------------------------------
% INDUSTRY KNOWLEDGE
%------------------------------------------------

\section{Industry Knowledge} 

\fbox{\includegraphics[page=5, scale=0.5, clip, trim=25mm 30mm 0mm 20mm]{Rplots.pdf}}

\sectionspace % Some whitespace after the section


%----------------------------------------------------------------------------------------

\end{minipage} % The end of the left column
\hfill
%
%----------------------------------------------------------------------------------------
%	MIDDLE COLUMN
%----------------------------------------------------------------------------------------
%
\begin{minipage}[t]{0.33\textwidth} % The middle column takes up 33% of the text width of the page

%------------------------------------------------
% TECH SKILLS
%------------------------------------------------

\section{Tech Skills}

\fbox{\includegraphics[page=2, scale=0.5, clip, trim=10mm 0mm 8mm 10mm]{Rplots.pdf}}

\sectionspace % Some whitespace after the section


%------------------------------------------------
% MADE WITH
%------------------------------------------------
\vspace{5mm}
\section{Made With}
\fbox{\includegraphics{logo.png}}
\sectionspace % Some whitespace after the section

%----------------------------------------------------------------------------------------

\end{minipage} % The end of the middle column
\hfill
%
%----------------------------------------------------------------------------------------
%	RIGHT COLUMN
%----------------------------------------------------------------------------------------
%
\begin{minipage}[t]{0.30\textwidth} % The right column takes up 30% of the text width of the page

\section{Other Stuff}

\fbox{\includegraphics[page=4, scale=0.5, clip, trim=20mm 30mm 15mm 30mm]{Rplots.pdf}}

\sectionspace % Some whitespace after the section


\section{Languages}

\fbox{\includegraphics[page=1, scale=0.45, clip, trim=10mm 10mm 10mm 20mm]{Rplots.pdf}}

\sectionspace % Some whitespace after the section

\end{minipage}


%----------------------------------------------------------------------------------------
%	SECOND PAGE (TEMPLATE)
%----------------------------------------------------------------------------------------
\iffalse  %put \iftrue to activate second page block of code

\newpage % Start a new page

\lastupdated % Print the Last Updated text at the top right

\namesection{Martina}{Manfrin}{ % Your name
\urlstyle{same}\url{linkedin.com/in/martinamanfrin} \\ % Your website, LinkedIn profile or other web address
\href{mailto:martina.manfrin87@gmail.com}{martina.manfrin87@gmail.com} | 340 7884910 % Your contact information
}

%----------------------------------------------------------------------------------------
%	LEFT COLUMN
%----------------------------------------------------------------------------------------
\begin{minipage}[t]{0.33\textwidth} % The left column takes up 33% of the text width of the page

%------------------------------------------------
% SUMMARY
%------------------------------------------------

\section{Summary} 

\subsection{Cornell University}

\descript{MEng in Computer Science}
\location{Expected Dec 2014 | Ithaca, NY \\ Cum. GPA: N/A}

\sectionspace % Some whitespace after the section


\end{minipage} % The end of the left column
\hfill
%
%----------------------------------------------------------------------------------------
%	RIGHT COLUMN
%----------------------------------------------------------------------------------------
%
\begin{minipage}[t]{0.66\textwidth} % The right column takes up 66% of the text width of the page

%------------------------------------------------
% WORK EXPERIENCE
%------------------------------------------------

\section{Work}



% EDUCATION
%------------------------------------------------

\section{Education}

\fbox{\includegraphics[page=6, scale=0.2,clip,trim=10mm 10mm 10mm 20mm]{Rplots.pdf}}

\sectionspace % Some whitespace after the section

%------------------------------------------------
\end{minipage} % The end of the right column

\fi

%----------------------------------------------------------------------------------------

%
%HERE BEGINS R CODE
%

<<p1, fig.cap="Foreign Languages", echo=FALSE>>=
#
#FOREIGN LANGUAGES
#

library(RColorBrewer)
#Read data from csv
df <- read.csv("ForeignLanguages.csv")
languages=df$Data
names(languages)=as.character(df$Label) 
#increase margin
par(mar=c(4,6,4,4))
# Horizontal Barplot:
barplot(languages, col=brewer.pal(3, "Accent"), horiz=T , las=1)
@


<<p2, fig.cap="Technological Skills", echo=FALSE>>=
#
#TECHNOLOGICAL SKILLS
#

library(RColorBrewer)
#Read data from csv
df <- read.csv("TechSkills.csv")
num <- df$Data
labels <- as.character(df$Label)
#Create a Data Frame
data <- data.frame(num, labels)
#Create an ordered Data Frame
data2  <- data[order(data[,1],decreasing=FALSE),]
#increase margin
par(mar=c(2,6,2,2))
# Horizontal Barplot
barplot(data2[,1],names.arg=data2[,2], col=brewer.pal(7, "Accent"), horiz=T ,las=1 )
@


<<p3, fig.cap="Thats Me", echo=FALSE>>=
#
#THAT'S ME!
#

library(RColorBrewer)
df <- read.csv("ThatsMe.csv")
Prop<- df$Data
Labs <- as.character(df$Label)
# Make the default Pie Plot
pie(Prop, labels=Labs , col=brewer.pal(4, "Accent"))

@


<<p4, fig.cap="Other Stuff", echo=FALSE>>=
#
#OTHER STUFF
#

#Charge the wordcloud library
library(wordcloud)
 
#Create a list of words (Random words concerning my work)
df <- read.csv("OtherStuff.csv")
a=as.character(df$Label)
 
#Give a frequency to each word of this list 
b=sample(seq(0,1,0.01) , length(a) , replace=TRUE) 
 
#The package will automatically make the wordcloud !
par(xpd=NA)
wordcloud(a , b , scale=c(5,0.7), colors=brewer.pal(6, "Dark2") , rot.per=0.35, use.r.layout=FALSE, random.order=TRUE)
@


<<p5, fig.cap="Industry Knowledge", echo=FALSE>>=
#
#INDUSTRY KNOWLEDGE
#

# Library
library(fmsb)

df <- read.csv("Industry.csv")
values<-df$Data
# Create data
data=as.data.frame(matrix( values , ncol=5))
colnames(data)=as.character(df$Label)

# To use the fmsb package, you need to add 2 lines to the dataframe: the max and min of each topic to show on the plot!
data=rbind(rep(20,10) , rep(0,10) , data)
par(xpd=NA)
 
# Custom the radarChart !
radarchart( data  , axistype=1 , 
 
    #custom polygon
    pcol=rgb(0.2,0.5,0.5,0.9) , pfcol=rgb(0.2,0.5,0.5,0.5) , plwd=4 , 
 
    #custom the grid
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.8)
@





\end{document}